# Checkov Configuration for Terraform Modules
# This configuration defines security and compliance scanning behavior
# Use with: checkov --config-file .checkov.yaml

# Compact output for cleaner results
compact: true

# Quiet mode - reduce verbosity
quiet: true

# Framework filters (only scan Terraform)
framework:
  - terraform
  - terraform_plan

# Output format
output: cli

# Directory to scan (default is current directory)
directory:
  - .

# Skip specific checks if needed (use sparingly and with justification)
# Format: CKV_<provider>_<number>
skip-check:
  # Registry modules use version constraints, not commit hashes
  - CKV_TF_1  # Ensure Terraform module sources use a commit hash
  
  # Add more skips as needed with justification:
  # - CKV_AZURE_35  # Storage account allows public blob access (if explicitly required)

# Soft fail mode - don't fail the build, just report (default: false)
# soft-fail: false

# Download external modules for scanning (recommended for thorough checks)
# download-external-modules: true

# External checks directory (for custom organizational policies)
# external-checks-dir:
#   - ./custom-policies

# Set baseline file to compare against
# baseline: checkov_baseline.json

# Additional configuration options:
# - branch: develop  # Specify branch name
# - repo-id: org/repo  # Repository identifier
# - check: [CKV_AZURE_1]  # Only run specific checks
# - skip-framework: [secrets]  # Skip specific frameworks

# For more options, see: https://www.checkov.io/2.Basics/CLI%20Command%20Reference.html
