# Checkov Configuration for Terraform Modules
# Security and compliance scanning for Terraform code

# Output settings
compact: true
quiet: true
output: cli

# Scan Terraform code
framework:
  - terraform

# Skip checks with justification
skip-check:
  # Registry modules use version constraints, not commit hashes
  - CKV_TF_1

# Note: Checkov ignores .terraform/ by default (via CKV_IGNORED_DIRECTORIES env var)
# To scan external modules, scan wrapper and .terraform/modules separately:
#   checkov -d . --config-file .checkov.yml --skip-path .terraform
#   checkov -d .terraform/modules/<module_name> --config-file .checkov.yml

# For more options: https://www.checkov.io/2.Basics/CLI%20Command%20Reference.html
